name: 'Release'

concurrency: release

on:
  push:
    tags:
      - v*.*.*

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:

  release_note:
    name: 'Release note'
    runs-on: [self-hosted]

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 'Extract latest changes'
        run: diff --changed-group-format='%>' --unchanged-group-format='' <( git show HEAD~1:CHANGELOG.md ) CHANGELOG.md > RELEASE_NOTES.md || true

      - name: 'Create release'
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
